git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --navigate --line-numbers
  # Command used when displaying the current branch git log in the main window
  branchLogCmd: git lg --color=always {{branchName}} --
  # Commands used to display git log of all branches in the main window, they will be cycled in order of appearance (array of strings)
  allBranchesLogCmds:
    - git lg --color=always --all
  # If true, periodically fetch from remote
  autoFetch: false
  # If true, pass the --all arg to git fetch
  fetchAll: false
gui:
  theme:
    selectedLineBgColor:
      - reverse
  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: '3'
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  showFileIcons: true
  # If true, increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: true
  enlargedSideViewLocation: top
customCommands:
  - key: <c-f>
    description: Fetch branch
    context: localBranches
    command: git fetch origin {{.SelectedLocalBranch.Name}}
  - key: <c-r>
    description: Rebase
    context: localBranches
    command: git pull --rebase origin {{.SelectedLocalBranch.Name}}

# Add to ~/.gitconfig:
# [delta]
# 	syntax-theme = Visual Studio Dark+
# Or: --syntax-theme="Visual Studio Dark+"

